FROM centos:7
MAINTAINER The CentOS Project <cloud-ops@centos.org>
LABEL Vendor="CentOS" \
      License=GPLv2 \
      Version=2.4.6-40

RUN yum -y --setopt=tsflags=nodocs update && \
    yum -y --setopt=tsflags=nodocs install httpd php php-gd php-ldap php-xml curl mod_ssl && \
    yum clean all

ADD httpd.sh /httpd.sh
RUN chmod -v +x /httpd.sh

CMD ["/httpd.sh"]
